server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url:
          - http://localhost:1111/
  application:
    name: WELCOME-API

management:
  endpoints:
    web:
      exposure:
        include: '*'

  tracing:
    sampling:
      probability=1:
        0:
        
msg : welcome to WELCOME-API